/* Generated by Yosys 0.9+4052 (git sha1 d061b0e, gcc 8.3.1 -fPIC -Os) */

module top(wb_clk_i, wb_rst_i, wbs_stb_i, wbs_cyc_i, wbs_we_i, wbs_sel_i, wbs_dat_i, wbs_adr_i, wbs_ack_o, wbs_dat_o, la_data_in, la_data_out, la_oenb, io_in, io_out, io_oeb, irq);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire ack_o;
  wire \addr[1] ;
  wire \addr[2] ;
  wire \addr[3] ;
  wire \cmp[0] ;
  wire \cmp[10] ;
  wire \cmp[11] ;
  wire \cmp[12] ;
  wire \cmp[13] ;
  wire \cmp[14] ;
  wire \cmp[1] ;
  wire \cmp[2] ;
  wire \cmp[3] ;
  wire \cmp[4] ;
  wire \cmp[5] ;
  wire \cmp[6] ;
  wire \cmp[7] ;
  wire \cmp[8] ;
  wire \cmp[9] ;
  wire \dat_o[0] ;
  wire \dat_o[10] ;
  wire \dat_o[11] ;
  wire \dat_o[12] ;
  wire \dat_o[13] ;
  wire \dat_o[14] ;
  wire \dat_o[15] ;
  wire \dat_o[1] ;
  wire \dat_o[2] ;
  wire \dat_o[3] ;
  wire \dat_o[4] ;
  wire \dat_o[5] ;
  wire \dat_o[6] ;
  wire \dat_o[7] ;
  wire \dat_o[8] ;
  wire \dat_o[9] ;
  wire \hi_z[0] ;
  wire \hi_z[10] ;
  wire \hi_z[11] ;
  wire \hi_z[12] ;
  wire \hi_z[13] ;
  wire \hi_z[14] ;
  wire \hi_z[1] ;
  wire \hi_z[2] ;
  wire \hi_z[3] ;
  wire \hi_z[4] ;
  wire \hi_z[5] ;
  wire \hi_z[6] ;
  wire \hi_z[7] ;
  wire \hi_z[8] ;
  wire \hi_z[9] ;
  input [37:0] io_in;
  output [37:0] io_oeb;
  output [37:0] io_out;
  output [2:0] irq;
  input [127:0] la_data_in;
  output [127:0] la_data_out;
  input [127:0] la_oenb;
  wire \mic.ce_pdm ;
  wire \mic.cnt1[0] ;
  wire \mic.cnt1[1] ;
  wire \mic.cnt1[2] ;
  wire \mic.cnt1[3] ;
  wire \mic.cnt2[0] ;
  wire \mic.cnt2[1] ;
  wire \mic.cnt2[2] ;
  wire \mic.cnt2[3] ;
  wire \mic.tmp1 ;
  wire \mic.tmp2 ;
  wire \pcmclk.ce_pcm ;
  wire \pcmclk.count[0] ;
  wire \pcmclk.count[1] ;
  wire \pcmclk.count[2] ;
  wire \pcmclk.count[3] ;
  wire \pcmclk.count[4] ;
  wire \pcmclk.count[5] ;
  wire \pcmclk.count[6] ;
  wire \pcmclk.count[7] ;
  wire \pcmclk.count[8] ;
  wire \pcmclk.count[9] ;
  wire \pcmclk.prescaler[0] ;
  wire \pcmclk.prescaler[1] ;
  wire \pcmclk.prescaler[2] ;
  wire \pcmclk.prescaler[3] ;
  wire \pcmclk.prescaler[4] ;
  wire \pcmclk.prescaler[5] ;
  wire \pcmclk.prescaler[6] ;
  wire \pcmclk.prescaler[7] ;
  wire \rdata[0] ;
  wire \rdata[1] ;
  wire \rdata[2] ;
  wire \rdata[3] ;
  wire \rdata[4] ;
  wire \rdata[5] ;
  wire \rdata[6] ;
  wire \rdata[7] ;
  wire strb_i;
  wire \valid_i[0] ;
  wire \valid_i[11] ;
  wire \valid_i[12] ;
  wire \valid_i[13] ;
  wire \valid_i[14] ;
  wire \valid_i[1] ;
  wire \valid_i[2] ;
  wire \valid_i[3] ;
  wire \valid_i[4] ;
  wire \valid_i[5] ;
  wire \valid_i[6] ;
  wire \valid_i[7] ;
  wire \valid_i[8] ;
  wire \valid_i[9] ;
  input wb_clk_i;
  input wb_rst_i;
  output wbs_ack_o;
  input [31:0] wbs_adr_i;
  input wbs_cyc_i;
  input [31:0] wbs_dat_i;
  output [31:0] wbs_dat_o;
  input [3:0] wbs_sel_i;
  input wbs_stb_i;
  input wbs_we_i;
  sky130_fd_sc_hd__inv_2 _259_ (
    .A(\mic.cnt2[1] ),
    .Y(_080_)
  );
  sky130_fd_sc_hd__inv_2 _260_ (
    .A(\mic.cnt2[2] ),
    .Y(_081_)
  );
  sky130_fd_sc_hd__inv_2 _261_ (
    .A(\mic.cnt2[3] ),
    .Y(_082_)
  );
  sky130_fd_sc_hd__inv_2 _262_ (
    .A(wb_rst_i),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_2 _263_ (
    .A(\mic.tmp2 ),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__inv_2 _264_ (
    .A(\mic.cnt2[0] ),
    .Y(_085_)
  );
  sky130_fd_sc_hd__and4_2 _265_ (
    .A(_080_),
    .B(_085_),
    .C(\mic.cnt2[2] ),
    .D(_082_),
    .X(_086_)
  );
  sky130_fd_sc_hd__a41o_2 _266_ (
    .A1(_080_),
    .A2(_081_),
    .A3(_082_),
    .A4(_084_),
    .B1(_086_),
    .X(_087_)
  );
  sky130_fd_sc_hd__inv_2 _267_ (
    .A(_087_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__inv_2 _268_ (
    .A(\mic.cnt1[1] ),
    .Y(_088_)
  );
  sky130_fd_sc_hd__inv_2 _269_ (
    .A(\mic.cnt1[3] ),
    .Y(_089_)
  );
  sky130_fd_sc_hd__inv_2 _270_ (
    .A(\mic.cnt1[2] ),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_2 _271_ (
    .A(\mic.tmp1 ),
    .B(_083_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__inv_2 _272_ (
    .A(\mic.cnt1[0] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__and4_2 _273_ (
    .A(_092_),
    .B(_088_),
    .C(_089_),
    .D(\mic.cnt1[2] ),
    .X(_093_)
  );
  sky130_fd_sc_hd__a41o_2 _274_ (
    .A1(_088_),
    .A2(_089_),
    .A3(_090_),
    .A4(_091_),
    .B1(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__inv_2 _275_ (
    .A(_094_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__and2_2 _276_ (
    .A(wbs_we_i),
    .B(wbs_sel_i[0]),
    .X(strb_i)
  );
  sky130_fd_sc_hd__or2_2 _277_ (
    .A(wbs_adr_i[3]),
    .B(wbs_adr_i[4]),
    .X(_095_)
  );
  sky130_fd_sc_hd__or3_2 _278_ (
    .A(wbs_adr_i[5]),
    .B(wbs_adr_i[6]),
    .C(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd__or2_2 _279_ (
    .A(wbs_adr_i[7]),
    .B(_096_),
    .X(_097_)
  );
  sky130_fd_sc_hd__inv_2 _280_ (
    .A(wbs_adr_i[28]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__or4b_2 _281_ (
    .A(wbs_adr_i[30]),
    .B(_098_),
    .C(wbs_adr_i[31]),
    .D_N(wbs_adr_i[29]),
    .X(_099_)
  );
  sky130_fd_sc_hd__and3b_2 _282_ (
    .A_N(_099_),
    .B(wbs_cyc_i),
    .C(wbs_stb_i),
    .X(_100_)
  );
  sky130_fd_sc_hd__inv_2 _283_ (
    .A(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__or2_2 _284_ (
    .A(_097_),
    .B(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__inv_2 _285_ (
    .A(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__and3_2 _286_ (
    .A(wbs_adr_i[2]),
    .B(strb_i),
    .C(_103_),
    .X(_104_)
  );
  sky130_fd_sc_hd__buf_1 _287_ (
    .A(_104_),
    .X(_105_)
  );
  sky130_fd_sc_hd__inv_2 _288_ (
    .A(_104_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__buf_1 _289_ (
    .A(_106_),
    .X(_107_)
  );
  sky130_fd_sc_hd__buf_1 _290_ (
    .A(_083_),
    .X(_108_)
  );
  sky130_fd_sc_hd__o221a_2 _291_ (
    .A1(\pcmclk.prescaler[7] ),
    .A2(_105_),
    .B1(wbs_dat_i[7]),
    .B2(_107_),
    .C1(_108_),
    .X(_077_)
  );
  sky130_fd_sc_hd__o221a_2 _292_ (
    .A1(\pcmclk.prescaler[6] ),
    .A2(_105_),
    .B1(wbs_dat_i[6]),
    .B2(_107_),
    .C1(_108_),
    .X(_076_)
  );
  sky130_fd_sc_hd__buf_1 _293_ (
    .A(wb_rst_i),
    .X(_109_)
  );
  sky130_fd_sc_hd__a221o_2 _294_ (
    .A1(wbs_dat_i[5]),
    .A2(_105_),
    .B1(\pcmclk.prescaler[5] ),
    .B2(_107_),
    .C1(_109_),
    .X(_075_)
  );
  sky130_fd_sc_hd__a221o_2 _295_ (
    .A1(wbs_dat_i[4]),
    .A2(_105_),
    .B1(\pcmclk.prescaler[4] ),
    .B2(_107_),
    .C1(_109_),
    .X(_074_)
  );
  sky130_fd_sc_hd__o221a_2 _296_ (
    .A1(\pcmclk.prescaler[3] ),
    .A2(_104_),
    .B1(wbs_dat_i[3]),
    .B2(_106_),
    .C1(_108_),
    .X(_073_)
  );
  sky130_fd_sc_hd__o221a_2 _297_ (
    .A1(\pcmclk.prescaler[2] ),
    .A2(_104_),
    .B1(wbs_dat_i[2]),
    .B2(_106_),
    .C1(_108_),
    .X(_072_)
  );
  sky130_fd_sc_hd__buf_1 _298_ (
    .A(_083_),
    .X(_110_)
  );
  sky130_fd_sc_hd__buf_1 _299_ (
    .A(_110_),
    .X(_111_)
  );
  sky130_fd_sc_hd__o221a_2 _300_ (
    .A1(\pcmclk.prescaler[1] ),
    .A2(_104_),
    .B1(wbs_dat_i[1]),
    .B2(_106_),
    .C1(_111_),
    .X(_071_)
  );
  sky130_fd_sc_hd__a221o_2 _301_ (
    .A1(wbs_dat_i[0]),
    .A2(_105_),
    .B1(\pcmclk.prescaler[0] ),
    .B2(_107_),
    .C1(_109_),
    .X(_070_)
  );
  sky130_fd_sc_hd__buf_1 _302_ (
    .A(_103_),
    .X(_112_)
  );
  sky130_fd_sc_hd__buf_1 _303_ (
    .A(_102_),
    .X(_113_)
  );
  sky130_fd_sc_hd__inv_2 _304_ (
    .A(\pcmclk.prescaler[7] ),
    .Y(_114_)
  );
  sky130_fd_sc_hd__inv_2 _305_ (
    .A(wbs_adr_i[2]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__buf_1 _306_ (
    .A(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__nor2_2 _307_ (
    .A(_114_),
    .B(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__o221a_2 _308_ (
    .A1(\rdata[7] ),
    .A2(_112_),
    .B1(_113_),
    .B2(_117_),
    .C1(_111_),
    .X(_069_)
  );
  sky130_fd_sc_hd__inv_2 _309_ (
    .A(\pcmclk.prescaler[6] ),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_2 _310_ (
    .A(_118_),
    .B(_116_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__o221a_2 _311_ (
    .A1(\rdata[6] ),
    .A2(_112_),
    .B1(_113_),
    .B2(_119_),
    .C1(_111_),
    .X(_068_)
  );
  sky130_fd_sc_hd__inv_2 _312_ (
    .A(\pcmclk.prescaler[5] ),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor2_2 _313_ (
    .A(_120_),
    .B(_116_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__o221a_2 _314_ (
    .A1(\rdata[5] ),
    .A2(_112_),
    .B1(_113_),
    .B2(_121_),
    .C1(_111_),
    .X(_067_)
  );
  sky130_fd_sc_hd__inv_2 _315_ (
    .A(\pcmclk.prescaler[4] ),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_2 _316_ (
    .A(_122_),
    .B(_116_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__o221a_2 _317_ (
    .A1(\rdata[4] ),
    .A2(_112_),
    .B1(_113_),
    .B2(_123_),
    .C1(_111_),
    .X(_066_)
  );
  sky130_fd_sc_hd__inv_2 _318_ (
    .A(\pcmclk.prescaler[3] ),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_2 _319_ (
    .A(_124_),
    .B(_116_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o221a_2 _320_ (
    .A1(\rdata[3] ),
    .A2(_112_),
    .B1(_113_),
    .B2(_125_),
    .C1(_110_),
    .X(_065_)
  );
  sky130_fd_sc_hd__inv_2 _321_ (
    .A(\pcmclk.prescaler[2] ),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nor2_2 _322_ (
    .A(_126_),
    .B(_115_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__o221a_2 _323_ (
    .A1(\rdata[2] ),
    .A2(_103_),
    .B1(_102_),
    .B2(_127_),
    .C1(_110_),
    .X(_064_)
  );
  sky130_fd_sc_hd__inv_2 _324_ (
    .A(\pcmclk.prescaler[1] ),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nor2_2 _325_ (
    .A(_128_),
    .B(_115_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o221a_2 _326_ (
    .A1(\rdata[1] ),
    .A2(_103_),
    .B1(_102_),
    .B2(_129_),
    .C1(_110_),
    .X(_063_)
  );
  sky130_fd_sc_hd__inv_2 _327_ (
    .A(\pcmclk.prescaler[0] ),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor2_2 _328_ (
    .A(_130_),
    .B(_115_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__o221a_2 _329_ (
    .A1(\rdata[0] ),
    .A2(_103_),
    .B1(_102_),
    .B2(_131_),
    .C1(_110_),
    .X(_062_)
  );
  sky130_fd_sc_hd__inv_2 _330_ (
    .A(\pcmclk.count[4] ),
    .Y(_132_)
  );
  sky130_fd_sc_hd__inv_2 _331_ (
    .A(\pcmclk.count[1] ),
    .Y(_133_)
  );
  sky130_fd_sc_hd__inv_2 _332_ (
    .A(\pcmclk.count[6] ),
    .Y(_134_)
  );
  sky130_fd_sc_hd__o22a_2 _333_ (
    .A1(\pcmclk.prescaler[6] ),
    .A2(_134_),
    .B1(_118_),
    .B2(\pcmclk.count[6] ),
    .X(_135_)
  );
  sky130_fd_sc_hd__o221a_2 _334_ (
    .A1(\pcmclk.prescaler[4] ),
    .A2(_132_),
    .B1(\pcmclk.prescaler[1] ),
    .B2(_133_),
    .C1(_135_),
    .X(_136_)
  );
  sky130_fd_sc_hd__inv_2 _335_ (
    .A(\pcmclk.count[2] ),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o22a_2 _336_ (
    .A1(_120_),
    .A2(\pcmclk.count[5] ),
    .B1(_126_),
    .B2(\pcmclk.count[2] ),
    .X(_138_)
  );
  sky130_fd_sc_hd__o221a_2 _337_ (
    .A1(\pcmclk.prescaler[2] ),
    .A2(_137_),
    .B1(_130_),
    .B2(\pcmclk.count[0] ),
    .C1(_138_),
    .X(_139_)
  );
  sky130_fd_sc_hd__inv_2 _338_ (
    .A(\pcmclk.count[5] ),
    .Y(_140_)
  );
  sky130_fd_sc_hd__inv_2 _339_ (
    .A(\pcmclk.count[3] ),
    .Y(_141_)
  );
  sky130_fd_sc_hd__or2_2 _340_ (
    .A(\pcmclk.prescaler[3] ),
    .B(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__o221a_2 _341_ (
    .A1(\pcmclk.prescaler[5] ),
    .A2(_140_),
    .B1(_128_),
    .B2(\pcmclk.count[1] ),
    .C1(_142_),
    .X(_143_)
  );
  sky130_fd_sc_hd__inv_2 _342_ (
    .A(\pcmclk.count[7] ),
    .Y(_144_)
  );
  sky130_fd_sc_hd__inv_2 _343_ (
    .A(\pcmclk.count[0] ),
    .Y(_145_)
  );
  sky130_fd_sc_hd__inv_2 _344_ (
    .A(\pcmclk.count[9] ),
    .Y(_146_)
  );
  sky130_fd_sc_hd__inv_2 _345_ (
    .A(\pcmclk.count[8] ),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o211a_2 _346_ (
    .A1(\pcmclk.prescaler[0] ),
    .A2(_145_),
    .B1(_146_),
    .C1(_147_),
    .X(_148_)
  );
  sky130_fd_sc_hd__o221a_2 _347_ (
    .A1(_122_),
    .A2(\pcmclk.count[4] ),
    .B1(_124_),
    .B2(\pcmclk.count[3] ),
    .C1(_148_),
    .X(_149_)
  );
  sky130_fd_sc_hd__o221a_2 _348_ (
    .A1(\pcmclk.prescaler[7] ),
    .A2(_144_),
    .B1(_114_),
    .B2(\pcmclk.count[7] ),
    .C1(_149_),
    .X(_150_)
  );
  sky130_fd_sc_hd__and4_2 _349_ (
    .A(_136_),
    .B(_139_),
    .C(_143_),
    .D(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hd__and2_2 _350_ (
    .A(_108_),
    .B(_151_),
    .X(_061_)
  );
  sky130_fd_sc_hd__inv_2 _351_ (
    .A(wb_clk_i),
    .Y(_040_)
  );
  sky130_fd_sc_hd__or2_2 _352_ (
    .A(_080_),
    .B(_085_),
    .X(_152_)
  );
  sky130_fd_sc_hd__or2_2 _353_ (
    .A(_109_),
    .B(_086_),
    .X(_153_)
  );
  sky130_fd_sc_hd__inv_2 _354_ (
    .A(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a31o_2 _355_ (
    .A1(\mic.cnt2[1] ),
    .A2(\mic.cnt2[0] ),
    .A3(\mic.cnt2[2] ),
    .B1(\mic.cnt2[3] ),
    .X(_155_)
  );
  sky130_fd_sc_hd__o311a_2 _356_ (
    .A1(_081_),
    .A2(_152_),
    .A3(_082_),
    .B1(_154_),
    .C1(_155_),
    .X(_060_)
  );
  sky130_fd_sc_hd__buf_1 _357_ (
    .A(_040_),
    .X(_039_)
  );
  sky130_fd_sc_hd__inv_2 _358_ (
    .A(_152_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o221a_2 _359_ (
    .A1(_081_),
    .A2(_152_),
    .B1(\mic.cnt2[2] ),
    .B2(_156_),
    .C1(_154_),
    .X(_059_)
  );
  sky130_fd_sc_hd__buf_1 _360_ (
    .A(_040_),
    .X(_038_)
  );
  sky130_fd_sc_hd__o211a_2 _361_ (
    .A1(\mic.cnt2[1] ),
    .A2(\mic.cnt2[0] ),
    .B1(_152_),
    .C1(_154_),
    .X(_058_)
  );
  sky130_fd_sc_hd__buf_1 _362_ (
    .A(_040_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nor2_2 _363_ (
    .A(\mic.cnt2[0] ),
    .B(_153_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__or2_2 _364_ (
    .A(_092_),
    .B(_088_),
    .X(_157_)
  );
  sky130_fd_sc_hd__or2_2 _365_ (
    .A(wb_rst_i),
    .B(_093_),
    .X(_158_)
  );
  sky130_fd_sc_hd__inv_2 _366_ (
    .A(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a31o_2 _367_ (
    .A1(\mic.cnt1[0] ),
    .A2(\mic.cnt1[1] ),
    .A3(\mic.cnt1[2] ),
    .B1(\mic.cnt1[3] ),
    .X(_160_)
  );
  sky130_fd_sc_hd__o311a_2 _368_ (
    .A1(_090_),
    .A2(_157_),
    .A3(_089_),
    .B1(_159_),
    .C1(_160_),
    .X(_056_)
  );
  sky130_fd_sc_hd__inv_2 _369_ (
    .A(_157_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o221a_2 _370_ (
    .A1(_090_),
    .A2(_157_),
    .B1(\mic.cnt1[2] ),
    .B2(_161_),
    .C1(_159_),
    .X(_055_)
  );
  sky130_fd_sc_hd__o211a_2 _371_ (
    .A1(\mic.cnt1[0] ),
    .A2(\mic.cnt1[1] ),
    .B1(_157_),
    .C1(_159_),
    .X(_054_)
  );
  sky130_fd_sc_hd__nor2_2 _372_ (
    .A(\mic.cnt1[0] ),
    .B(_158_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_2 _373_ (
    .A(_145_),
    .B(_133_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_2 _374_ (
    .A(\pcmclk.count[2] ),
    .B(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__or2_2 _375_ (
    .A(_141_),
    .B(_163_),
    .X(_164_)
  );
  sky130_fd_sc_hd__or2_2 _376_ (
    .A(_132_),
    .B(_164_),
    .X(_165_)
  );
  sky130_fd_sc_hd__or2_2 _377_ (
    .A(_140_),
    .B(_165_),
    .X(_166_)
  );
  sky130_fd_sc_hd__or3_2 _378_ (
    .A(_134_),
    .B(_166_),
    .C(_144_),
    .X(_167_)
  );
  sky130_fd_sc_hd__or2_2 _379_ (
    .A(_147_),
    .B(_167_),
    .X(_168_)
  );
  sky130_fd_sc_hd__inv_2 _380_ (
    .A(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__or2_2 _381_ (
    .A(wb_rst_i),
    .B(_151_),
    .X(_170_)
  );
  sky130_fd_sc_hd__inv_2 _382_ (
    .A(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__buf_1 _383_ (
    .A(_171_),
    .X(_172_)
  );
  sky130_fd_sc_hd__o221a_2 _384_ (
    .A1(\pcmclk.count[9] ),
    .A2(_169_),
    .B1(_146_),
    .B2(_168_),
    .C1(_172_),
    .X(_052_)
  );
  sky130_fd_sc_hd__inv_2 _385_ (
    .A(_167_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o211a_2 _386_ (
    .A1(\pcmclk.count[8] ),
    .A2(_173_),
    .B1(_168_),
    .C1(_172_),
    .X(_051_)
  );
  sky130_fd_sc_hd__o21a_2 _387_ (
    .A1(_134_),
    .A2(_166_),
    .B1(_144_),
    .X(_174_)
  );
  sky130_fd_sc_hd__nor3_2 _388_ (
    .A(_173_),
    .B(_170_),
    .C(_174_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__inv_2 _389_ (
    .A(_166_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__o221a_2 _390_ (
    .A1(_134_),
    .A2(_166_),
    .B1(\pcmclk.count[6] ),
    .B2(_175_),
    .C1(_172_),
    .X(_049_)
  );
  sky130_fd_sc_hd__a211oi_2 _391_ (
    .A1(_140_),
    .A2(_165_),
    .B1(_175_),
    .C1(_170_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__inv_2 _392_ (
    .A(_164_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__o211a_2 _393_ (
    .A1(\pcmclk.count[4] ),
    .A2(_176_),
    .B1(_165_),
    .C1(_172_),
    .X(_047_)
  );
  sky130_fd_sc_hd__a211oi_2 _394_ (
    .A1(_141_),
    .A2(_163_),
    .B1(_176_),
    .C1(_170_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o211a_2 _395_ (
    .A1(\pcmclk.count[2] ),
    .A2(_162_),
    .B1(_163_),
    .C1(_172_),
    .X(_045_)
  );
  sky130_fd_sc_hd__o221a_2 _396_ (
    .A1(_145_),
    .A2(_133_),
    .B1(\pcmclk.count[0] ),
    .B2(\pcmclk.count[1] ),
    .C1(_171_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nor2_2 _397_ (
    .A(\pcmclk.count[0] ),
    .B(_170_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__buf_1 _398_ (
    .A(_101_),
    .X(_177_)
  );
  sky130_fd_sc_hd__buf_1 _399_ (
    .A(_177_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nor2_2 _400_ (
    .A(_109_),
    .B(_178_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_2 _401_ (
    .A(wbs_adr_i[3]),
    .Y(\addr[1] )
  );
  sky130_fd_sc_hd__and4_2 _402_ (
    .A(_088_),
    .B(_089_),
    .C(_090_),
    .D(\mic.cnt1[0] ),
    .X(\mic.ce_pdm )
  );
  sky130_fd_sc_hd__nand4_2 _403_ (
    .A(\hi_z[5] ),
    .B(\hi_z[4] ),
    .C(\hi_z[7] ),
    .D(\hi_z[6] ),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand4_2 _404_ (
    .A(\hi_z[1] ),
    .B(\hi_z[0] ),
    .C(\hi_z[3] ),
    .D(\hi_z[2] ),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nand3_2 _405_ (
    .A(\hi_z[13] ),
    .B(\hi_z[12] ),
    .C(\hi_z[14] ),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand4_2 _406_ (
    .A(\hi_z[9] ),
    .B(\hi_z[8] ),
    .C(\hi_z[11] ),
    .D(\hi_z[10] ),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nor4_2 _407_ (
    .A(_179_),
    .B(_180_),
    .C(_181_),
    .D(_182_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__buf_1 _408_ (
    .A(_183_),
    .X(_184_)
  );
  sky130_fd_sc_hd__nor2b_2 _409_ (
    .A(_184_),
    .B_N(\dat_o[0] ),
    .Y(_028_)
  );
  sky130_fd_sc_hd__or2_2 _410_ (
    .A(wbs_adr_i[3]),
    .B(_099_),
    .X(_185_)
  );
  sky130_fd_sc_hd__inv_2 _411_ (
    .A(_185_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2b_2 _412_ (
    .A(_184_),
    .B_N(\dat_o[1] ),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2b_2 _413_ (
    .A(_184_),
    .B_N(\dat_o[2] ),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2b_2 _414_ (
    .A(_184_),
    .B_N(\dat_o[3] ),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2b_2 _415_ (
    .A(_184_),
    .B_N(\dat_o[4] ),
    .Y(_033_)
  );
  sky130_fd_sc_hd__buf_1 _416_ (
    .A(_183_),
    .X(_186_)
  );
  sky130_fd_sc_hd__nor2b_2 _417_ (
    .A(_186_),
    .B_N(\dat_o[5] ),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor2b_2 _418_ (
    .A(_186_),
    .B_N(\dat_o[6] ),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor2b_2 _419_ (
    .A(_186_),
    .B_N(\dat_o[7] ),
    .Y(_036_)
  );
  sky130_fd_sc_hd__buf_1 _420_ (
    .A(_185_),
    .X(_187_)
  );
  sky130_fd_sc_hd__and3b_2 _421_ (
    .A_N(_186_),
    .B(_187_),
    .C(\dat_o[8] ),
    .X(wbs_dat_o[8])
  );
  sky130_fd_sc_hd__and3b_2 _422_ (
    .A_N(_186_),
    .B(_187_),
    .C(\dat_o[9] ),
    .X(wbs_dat_o[9])
  );
  sky130_fd_sc_hd__buf_1 _423_ (
    .A(_183_),
    .X(_188_)
  );
  sky130_fd_sc_hd__and3b_2 _424_ (
    .A_N(_188_),
    .B(_187_),
    .C(\dat_o[10] ),
    .X(wbs_dat_o[10])
  );
  sky130_fd_sc_hd__and3b_2 _425_ (
    .A_N(_188_),
    .B(_187_),
    .C(\dat_o[11] ),
    .X(wbs_dat_o[11])
  );
  sky130_fd_sc_hd__and3b_2 _426_ (
    .A_N(_188_),
    .B(_187_),
    .C(\dat_o[12] ),
    .X(wbs_dat_o[12])
  );
  sky130_fd_sc_hd__and3b_2 _427_ (
    .A_N(_188_),
    .B(_185_),
    .C(\dat_o[13] ),
    .X(wbs_dat_o[13])
  );
  sky130_fd_sc_hd__and3b_2 _428_ (
    .A_N(_188_),
    .B(_185_),
    .C(\dat_o[14] ),
    .X(wbs_dat_o[14])
  );
  sky130_fd_sc_hd__and3b_2 _429_ (
    .A_N(_183_),
    .B(_185_),
    .C(\dat_o[15] ),
    .X(wbs_dat_o[31])
  );
  sky130_fd_sc_hd__nor2_2 _430_ (
    .A(\mic.tmp2 ),
    .B(\mic.tmp1 ),
    .Y(io_out[0])
  );
  sky130_fd_sc_hd__and2_2 _431_ (
    .A(wbs_ack_o),
    .B(_029_),
    .X(wbs_ack_o)
  );
  sky130_fd_sc_hd__or3_2 _432_ (
    .A(wbs_adr_i[7]),
    .B(wbs_adr_i[8]),
    .C(_096_),
    .X(_189_)
  );
  sky130_fd_sc_hd__inv_2 _433_ (
    .A(wbs_adr_i[9]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__inv_2 _434_ (
    .A(_189_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__o22a_2 _435_ (
    .A1(wbs_adr_i[9]),
    .A2(_189_),
    .B1(_190_),
    .B2(_191_),
    .X(_192_)
  );
  sky130_fd_sc_hd__and2_2 _436_ (
    .A(wbs_adr_i[8]),
    .B(_097_),
    .X(_193_)
  );
  sky130_fd_sc_hd__or2_2 _437_ (
    .A(_191_),
    .B(_193_),
    .X(_194_)
  );
  sky130_fd_sc_hd__or2b_2 _438_ (
    .A(_192_),
    .B_N(_194_),
    .X(_195_)
  );
  sky130_fd_sc_hd__inv_2 _439_ (
    .A(wbs_adr_i[7]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__inv_2 _440_ (
    .A(_096_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o21a_2 _441_ (
    .A1(wbs_adr_i[5]),
    .A2(_095_),
    .B1(wbs_adr_i[6]),
    .X(_198_)
  );
  sky130_fd_sc_hd__or2_2 _442_ (
    .A(_197_),
    .B(_198_),
    .X(_199_)
  );
  sky130_fd_sc_hd__or2_2 _443_ (
    .A(_196_),
    .B(_199_),
    .X(_200_)
  );
  sky130_fd_sc_hd__inv_2 _444_ (
    .A(wbs_adr_i[10]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__o21a_2 _445_ (
    .A1(wbs_adr_i[9]),
    .A2(_189_),
    .B1(wbs_adr_i[10]),
    .X(_202_)
  );
  sky130_fd_sc_hd__a31o_2 _446_ (
    .A1(_190_),
    .A2(_201_),
    .A3(_191_),
    .B1(_202_),
    .X(_203_)
  );
  sky130_fd_sc_hd__or2_2 _447_ (
    .A(_200_),
    .B(_203_),
    .X(_204_)
  );
  sky130_fd_sc_hd__or2_2 _448_ (
    .A(_195_),
    .B(_204_),
    .X(_205_)
  );
  sky130_fd_sc_hd__nor2_2 _449_ (
    .A(_178_),
    .B(_205_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__o21ai_2 _450_ (
    .A1(_196_),
    .A2(_197_),
    .B1(_097_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__nand2_2 _451_ (
    .A(_199_),
    .B(_206_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__or2_2 _452_ (
    .A(_203_),
    .B(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd__or3_2 _453_ (
    .A(_190_),
    .B(_191_),
    .C(_193_),
    .X(_209_)
  );
  sky130_fd_sc_hd__or2_2 _454_ (
    .A(_208_),
    .B(_209_),
    .X(_210_)
  );
  sky130_fd_sc_hd__nor2_2 _455_ (
    .A(_178_),
    .B(_210_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__or2b_2 _456_ (
    .A(_206_),
    .B_N(_199_),
    .X(_211_)
  );
  sky130_fd_sc_hd__or2_2 _457_ (
    .A(_203_),
    .B(_211_),
    .X(_212_)
  );
  sky130_fd_sc_hd__or2_2 _458_ (
    .A(_209_),
    .B(_212_),
    .X(_213_)
  );
  sky130_fd_sc_hd__nor2_2 _459_ (
    .A(_178_),
    .B(_213_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__or2_2 _460_ (
    .A(wbs_adr_i[7]),
    .B(_199_),
    .X(_214_)
  );
  sky130_fd_sc_hd__or2_2 _461_ (
    .A(_203_),
    .B(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd__or2_2 _462_ (
    .A(_209_),
    .B(_215_),
    .X(_216_)
  );
  sky130_fd_sc_hd__nor2_2 _463_ (
    .A(_178_),
    .B(_216_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__buf_1 _464_ (
    .A(_177_),
    .X(_217_)
  );
  sky130_fd_sc_hd__nand2_2 _465_ (
    .A(_192_),
    .B(_194_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__or2_2 _466_ (
    .A(_208_),
    .B(_218_),
    .X(_219_)
  );
  sky130_fd_sc_hd__nor2_2 _467_ (
    .A(_217_),
    .B(_219_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__or2_2 _468_ (
    .A(_204_),
    .B(_218_),
    .X(_220_)
  );
  sky130_fd_sc_hd__nor2_2 _469_ (
    .A(_217_),
    .B(_220_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__or2_2 _470_ (
    .A(_212_),
    .B(_218_),
    .X(_221_)
  );
  sky130_fd_sc_hd__nor2_2 _471_ (
    .A(_217_),
    .B(_221_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__or2_2 _472_ (
    .A(_215_),
    .B(_218_),
    .X(_222_)
  );
  sky130_fd_sc_hd__nor2_2 _473_ (
    .A(_217_),
    .B(_222_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__or3_2 _474_ (
    .A(wbs_adr_i[9]),
    .B(wbs_adr_i[10]),
    .C(_194_),
    .X(_223_)
  );
  sky130_fd_sc_hd__or2_2 _475_ (
    .A(_101_),
    .B(_223_),
    .X(_224_)
  );
  sky130_fd_sc_hd__nor2_2 _476_ (
    .A(_207_),
    .B(_224_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_2 _477_ (
    .A(_200_),
    .B(_224_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_2 _478_ (
    .A(_211_),
    .B(_224_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_2 _479_ (
    .A(_214_),
    .B(_224_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__or2_2 _480_ (
    .A(_195_),
    .B(_212_),
    .X(_225_)
  );
  sky130_fd_sc_hd__nor2_2 _481_ (
    .A(_217_),
    .B(_225_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__buf_1 _482_ (
    .A(_101_),
    .X(_226_)
  );
  sky130_fd_sc_hd__or2_2 _483_ (
    .A(_195_),
    .B(_215_),
    .X(_227_)
  );
  sky130_fd_sc_hd__nor2_2 _484_ (
    .A(_226_),
    .B(_227_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and4_2 _485_ (
    .A(_210_),
    .B(_227_),
    .C(_213_),
    .D(_225_),
    .X(_228_)
  );
  sky130_fd_sc_hd__buf_1 _486_ (
    .A(_228_),
    .X(_229_)
  );
  sky130_fd_sc_hd__inv_2 _487_ (
    .A(_223_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__buf_1 _488_ (
    .A(_230_),
    .X(_231_)
  );
  sky130_fd_sc_hd__inv_2 _489_ (
    .A(_205_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__a21oi_2 _490_ (
    .A1(_214_),
    .A2(_231_),
    .B1(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__inv_2 _491_ (
    .A(_216_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__inv_2 _492_ (
    .A(_220_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__or2_2 _493_ (
    .A(_234_),
    .B(_235_),
    .X(_236_)
  );
  sky130_fd_sc_hd__inv_2 _494_ (
    .A(_222_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nand2_2 _495_ (
    .A(_219_),
    .B(_221_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__or2_2 _496_ (
    .A(_237_),
    .B(_238_),
    .X(_239_)
  );
  sky130_fd_sc_hd__or2_2 _497_ (
    .A(_236_),
    .B(_239_),
    .X(_240_)
  );
  sky130_fd_sc_hd__inv_2 _498_ (
    .A(_240_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__a31oi_2 _499_ (
    .A1(_229_),
    .A2(_233_),
    .A3(_241_),
    .B1(_226_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a21oi_2 _500_ (
    .A1(_211_),
    .A2(_231_),
    .B1(_232_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a31oi_2 _501_ (
    .A1(_229_),
    .A2(_242_),
    .A3(_241_),
    .B1(_226_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21oi_2 _502_ (
    .A1(_200_),
    .A2(_231_),
    .B1(_232_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__a31oi_2 _503_ (
    .A1(_229_),
    .A2(_243_),
    .A3(_241_),
    .B1(_226_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a21oi_2 _504_ (
    .A1(_207_),
    .A2(_231_),
    .B1(_232_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a31oi_2 _505_ (
    .A1(_229_),
    .A2(_244_),
    .A3(_241_),
    .B1(_226_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__inv_2 _506_ (
    .A(_213_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__inv_2 _507_ (
    .A(_210_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__inv_2 _508_ (
    .A(_227_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nand2_2 _509_ (
    .A(_205_),
    .B(_225_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__or2_2 _510_ (
    .A(_230_),
    .B(_248_),
    .X(_249_)
  );
  sky130_fd_sc_hd__or3_2 _511_ (
    .A(_246_),
    .B(_247_),
    .C(_249_),
    .X(_250_)
  );
  sky130_fd_sc_hd__buf_1 _512_ (
    .A(_100_),
    .X(_251_)
  );
  sky130_fd_sc_hd__o41a_2 _513_ (
    .A1(_245_),
    .A2(_238_),
    .A3(_236_),
    .A4(_250_),
    .B1(_251_),
    .X(_023_)
  );
  sky130_fd_sc_hd__or2_2 _514_ (
    .A(_245_),
    .B(_234_),
    .X(_252_)
  );
  sky130_fd_sc_hd__or2_2 _515_ (
    .A(_235_),
    .B(_237_),
    .X(_253_)
  );
  sky130_fd_sc_hd__nor2_2 _516_ (
    .A(_252_),
    .B(_253_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__inv_2 _517_ (
    .A(_250_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__a31oi_2 _518_ (
    .A1(_219_),
    .A2(_254_),
    .A3(_255_),
    .B1(_177_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o31a_2 _519_ (
    .A1(_239_),
    .A2(_252_),
    .A3(_250_),
    .B1(_251_),
    .X(_025_)
  );
  sky130_fd_sc_hd__a31oi_2 _520_ (
    .A1(_221_),
    .A2(_254_),
    .A3(_255_),
    .B1(_177_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o41a_2 _521_ (
    .A1(_245_),
    .A2(_238_),
    .A3(_253_),
    .A4(_250_),
    .B1(_251_),
    .X(_027_)
  );
  sky130_fd_sc_hd__o21a_2 _522_ (
    .A1(_240_),
    .A2(_250_),
    .B1(_251_),
    .X(_014_)
  );
  sky130_fd_sc_hd__or2_2 _523_ (
    .A(_245_),
    .B(_247_),
    .X(_256_)
  );
  sky130_fd_sc_hd__o31a_2 _524_ (
    .A1(_249_),
    .A2(_256_),
    .A3(_240_),
    .B1(_251_),
    .X(_015_)
  );
  sky130_fd_sc_hd__or2_2 _525_ (
    .A(_246_),
    .B(_231_),
    .X(_257_)
  );
  sky130_fd_sc_hd__o41a_2 _526_ (
    .A1(_245_),
    .A2(_248_),
    .A3(_257_),
    .A4(_240_),
    .B1(_100_),
    .X(_016_)
  );
  sky130_fd_sc_hd__o41a_2 _527_ (
    .A1(_232_),
    .A2(_256_),
    .A3(_257_),
    .A4(_240_),
    .B1(_100_),
    .X(_017_)
  );
  sky130_fd_sc_hd__a31oi_2 _528_ (
    .A1(_223_),
    .A2(_229_),
    .A3(_241_),
    .B1(_177_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21bo_2 _529_ (
    .A1(wbs_adr_i[3]),
    .A2(wbs_adr_i[4]),
    .B1_N(_095_),
    .X(\addr[2] )
  );
  sky130_fd_sc_hd__a2bb2o_2 _530_ (
    .A1_N(wbs_adr_i[5]),
    .A2_N(_095_),
    .B1(wbs_adr_i[5]),
    .B2(_095_),
    .X(\addr[3] )
  );
  sky130_fd_sc_hd__buf_1 _531_ (
    .A(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__conb_1 _532_ (
    .HI(io_oeb[0])
  );
  sky130_fd_sc_hd__conb_1 _533_ (
    .LO(_258_)
  );
  sky130_fd_sc_hd__conb_1 _534_ (
    .LO(io_oeb[1])
  );
  sky130_fd_sc_hd__conb_1 _535_ (
    .LO(io_oeb[2])
  );
  sky130_fd_sc_hd__conb_1 _536_ (
    .LO(io_oeb[3])
  );
  sky130_fd_sc_hd__conb_1 _537_ (
    .LO(io_oeb[4])
  );
  sky130_fd_sc_hd__conb_1 _538_ (
    .LO(io_oeb[5])
  );
  sky130_fd_sc_hd__conb_1 _539_ (
    .LO(io_oeb[6])
  );
  sky130_fd_sc_hd__conb_1 _540_ (
    .LO(io_oeb[7])
  );
  sky130_fd_sc_hd__conb_1 _541_ (
    .LO(io_oeb[8])
  );
  sky130_fd_sc_hd__conb_1 _542_ (
    .LO(io_oeb[9])
  );
  sky130_fd_sc_hd__conb_1 _543_ (
    .LO(io_oeb[10])
  );
  sky130_fd_sc_hd__conb_1 _544_ (
    .LO(io_oeb[11])
  );
  sky130_fd_sc_hd__conb_1 _545_ (
    .LO(io_oeb[12])
  );
  sky130_fd_sc_hd__conb_1 _546_ (
    .LO(io_oeb[13])
  );
  sky130_fd_sc_hd__conb_1 _547_ (
    .LO(io_oeb[14])
  );
  sky130_fd_sc_hd__conb_1 _548_ (
    .LO(io_oeb[15])
  );
  sky130_fd_sc_hd__conb_1 _549_ (
    .LO(io_oeb[16])
  );
  sky130_fd_sc_hd__conb_1 _550_ (
    .LO(io_oeb[17])
  );
  sky130_fd_sc_hd__conb_1 _551_ (
    .LO(io_oeb[18])
  );
  sky130_fd_sc_hd__conb_1 _552_ (
    .LO(io_oeb[19])
  );
  sky130_fd_sc_hd__conb_1 _553_ (
    .LO(io_oeb[20])
  );
  sky130_fd_sc_hd__conb_1 _554_ (
    .LO(io_oeb[21])
  );
  sky130_fd_sc_hd__conb_1 _555_ (
    .LO(io_oeb[22])
  );
  sky130_fd_sc_hd__conb_1 _556_ (
    .LO(io_oeb[23])
  );
  sky130_fd_sc_hd__conb_1 _557_ (
    .LO(io_oeb[24])
  );
  sky130_fd_sc_hd__conb_1 _558_ (
    .LO(io_oeb[25])
  );
  sky130_fd_sc_hd__conb_1 _559_ (
    .LO(io_oeb[26])
  );
  sky130_fd_sc_hd__conb_1 _560_ (
    .LO(io_oeb[27])
  );
  sky130_fd_sc_hd__conb_1 _561_ (
    .LO(io_oeb[28])
  );
  sky130_fd_sc_hd__conb_1 _562_ (
    .LO(io_oeb[29])
  );
  sky130_fd_sc_hd__conb_1 _563_ (
    .LO(io_oeb[30])
  );
  sky130_fd_sc_hd__conb_1 _564_ (
    .LO(io_oeb[31])
  );
  sky130_fd_sc_hd__conb_1 _565_ (
    .LO(io_oeb[32])
  );
  sky130_fd_sc_hd__conb_1 _566_ (
    .LO(io_oeb[33])
  );
  sky130_fd_sc_hd__conb_1 _567_ (
    .LO(io_oeb[34])
  );
  sky130_fd_sc_hd__conb_1 _568_ (
    .LO(io_oeb[35])
  );
  sky130_fd_sc_hd__conb_1 _569_ (
    .LO(io_oeb[36])
  );
  sky130_fd_sc_hd__conb_1 _570_ (
    .LO(io_oeb[37])
  );
  sky130_fd_sc_hd__conb_1 _571_ (
    .LO(io_out[1])
  );
  sky130_fd_sc_hd__conb_1 _572_ (
    .LO(io_out[2])
  );
  sky130_fd_sc_hd__conb_1 _573_ (
    .LO(io_out[3])
  );
  sky130_fd_sc_hd__conb_1 _574_ (
    .LO(io_out[4])
  );
  sky130_fd_sc_hd__conb_1 _575_ (
    .LO(io_out[5])
  );
  sky130_fd_sc_hd__conb_1 _576_ (
    .LO(io_out[6])
  );
  sky130_fd_sc_hd__conb_1 _577_ (
    .LO(io_out[7])
  );
  sky130_fd_sc_hd__conb_1 _578_ (
    .LO(io_out[8])
  );
  sky130_fd_sc_hd__conb_1 _579_ (
    .LO(io_out[9])
  );
  sky130_fd_sc_hd__conb_1 _580_ (
    .LO(io_out[10])
  );
  sky130_fd_sc_hd__conb_1 _581_ (
    .LO(io_out[11])
  );
  sky130_fd_sc_hd__conb_1 _582_ (
    .LO(io_out[12])
  );
  sky130_fd_sc_hd__conb_1 _583_ (
    .LO(io_out[13])
  );
  sky130_fd_sc_hd__conb_1 _584_ (
    .LO(io_out[14])
  );
  sky130_fd_sc_hd__conb_1 _585_ (
    .LO(io_out[15])
  );
  sky130_fd_sc_hd__conb_1 _586_ (
    .LO(io_out[16])
  );
  sky130_fd_sc_hd__conb_1 _587_ (
    .LO(io_out[17])
  );
  sky130_fd_sc_hd__conb_1 _588_ (
    .LO(io_out[18])
  );
  sky130_fd_sc_hd__conb_1 _589_ (
    .LO(io_out[19])
  );
  sky130_fd_sc_hd__conb_1 _590_ (
    .LO(io_out[20])
  );
  sky130_fd_sc_hd__conb_1 _591_ (
    .LO(io_out[21])
  );
  sky130_fd_sc_hd__conb_1 _592_ (
    .LO(io_out[22])
  );
  sky130_fd_sc_hd__conb_1 _593_ (
    .LO(io_out[23])
  );
  sky130_fd_sc_hd__conb_1 _594_ (
    .LO(io_out[24])
  );
  sky130_fd_sc_hd__conb_1 _595_ (
    .LO(io_out[25])
  );
  sky130_fd_sc_hd__conb_1 _596_ (
    .LO(io_out[26])
  );
  sky130_fd_sc_hd__conb_1 _597_ (
    .LO(io_out[27])
  );
  sky130_fd_sc_hd__conb_1 _598_ (
    .LO(io_out[28])
  );
  sky130_fd_sc_hd__conb_1 _599_ (
    .LO(io_out[29])
  );
  sky130_fd_sc_hd__conb_1 _600_ (
    .LO(io_out[30])
  );
  sky130_fd_sc_hd__conb_1 _601_ (
    .LO(io_out[31])
  );
  sky130_fd_sc_hd__conb_1 _602_ (
    .LO(io_out[32])
  );
  sky130_fd_sc_hd__conb_1 _603_ (
    .LO(io_out[33])
  );
  sky130_fd_sc_hd__conb_1 _604_ (
    .LO(io_out[34])
  );
  sky130_fd_sc_hd__conb_1 _605_ (
    .LO(io_out[35])
  );
  sky130_fd_sc_hd__conb_1 _606_ (
    .LO(io_out[36])
  );
  sky130_fd_sc_hd__conb_1 _607_ (
    .LO(io_out[37])
  );
  sky130_fd_sc_hd__conb_1 _608_ (
    .LO(irq[0])
  );
  sky130_fd_sc_hd__conb_1 _609_ (
    .LO(irq[1])
  );
  sky130_fd_sc_hd__conb_1 _610_ (
    .LO(irq[2])
  );
  sky130_fd_sc_hd__conb_1 _611_ (
    .LO(la_data_out[0])
  );
  sky130_fd_sc_hd__conb_1 _612_ (
    .LO(la_data_out[1])
  );
  sky130_fd_sc_hd__conb_1 _613_ (
    .LO(la_data_out[2])
  );
  sky130_fd_sc_hd__conb_1 _614_ (
    .LO(la_data_out[3])
  );
  sky130_fd_sc_hd__conb_1 _615_ (
    .LO(la_data_out[4])
  );
  sky130_fd_sc_hd__conb_1 _616_ (
    .LO(la_data_out[5])
  );
  sky130_fd_sc_hd__conb_1 _617_ (
    .LO(la_data_out[6])
  );
  sky130_fd_sc_hd__conb_1 _618_ (
    .LO(la_data_out[7])
  );
  sky130_fd_sc_hd__conb_1 _619_ (
    .LO(la_data_out[8])
  );
  sky130_fd_sc_hd__conb_1 _620_ (
    .LO(la_data_out[9])
  );
  sky130_fd_sc_hd__conb_1 _621_ (
    .LO(la_data_out[10])
  );
  sky130_fd_sc_hd__conb_1 _622_ (
    .LO(la_data_out[11])
  );
  sky130_fd_sc_hd__conb_1 _623_ (
    .LO(la_data_out[12])
  );
  sky130_fd_sc_hd__conb_1 _624_ (
    .LO(la_data_out[13])
  );
  sky130_fd_sc_hd__conb_1 _625_ (
    .LO(la_data_out[14])
  );
  sky130_fd_sc_hd__conb_1 _626_ (
    .LO(la_data_out[15])
  );
  sky130_fd_sc_hd__conb_1 _627_ (
    .LO(la_data_out[16])
  );
  sky130_fd_sc_hd__conb_1 _628_ (
    .LO(la_data_out[17])
  );
  sky130_fd_sc_hd__conb_1 _629_ (
    .LO(la_data_out[18])
  );
  sky130_fd_sc_hd__conb_1 _630_ (
    .LO(la_data_out[19])
  );
  sky130_fd_sc_hd__conb_1 _631_ (
    .LO(la_data_out[20])
  );
  sky130_fd_sc_hd__conb_1 _632_ (
    .LO(la_data_out[21])
  );
  sky130_fd_sc_hd__conb_1 _633_ (
    .LO(la_data_out[22])
  );
  sky130_fd_sc_hd__conb_1 _634_ (
    .LO(la_data_out[23])
  );
  sky130_fd_sc_hd__conb_1 _635_ (
    .LO(la_data_out[24])
  );
  sky130_fd_sc_hd__conb_1 _636_ (
    .LO(la_data_out[25])
  );
  sky130_fd_sc_hd__conb_1 _637_ (
    .LO(la_data_out[26])
  );
  sky130_fd_sc_hd__conb_1 _638_ (
    .LO(la_data_out[27])
  );
  sky130_fd_sc_hd__conb_1 _639_ (
    .LO(la_data_out[28])
  );
  sky130_fd_sc_hd__conb_1 _640_ (
    .LO(la_data_out[29])
  );
  sky130_fd_sc_hd__conb_1 _641_ (
    .LO(la_data_out[30])
  );
  sky130_fd_sc_hd__conb_1 _642_ (
    .LO(la_data_out[31])
  );
  sky130_fd_sc_hd__conb_1 _643_ (
    .LO(la_data_out[32])
  );
  sky130_fd_sc_hd__conb_1 _644_ (
    .LO(la_data_out[33])
  );
  sky130_fd_sc_hd__conb_1 _645_ (
    .LO(la_data_out[34])
  );
  sky130_fd_sc_hd__conb_1 _646_ (
    .LO(la_data_out[35])
  );
  sky130_fd_sc_hd__conb_1 _647_ (
    .LO(la_data_out[36])
  );
  sky130_fd_sc_hd__conb_1 _648_ (
    .LO(la_data_out[37])
  );
  sky130_fd_sc_hd__conb_1 _649_ (
    .LO(la_data_out[38])
  );
  sky130_fd_sc_hd__conb_1 _650_ (
    .LO(la_data_out[39])
  );
  sky130_fd_sc_hd__conb_1 _651_ (
    .LO(la_data_out[40])
  );
  sky130_fd_sc_hd__conb_1 _652_ (
    .LO(la_data_out[41])
  );
  sky130_fd_sc_hd__conb_1 _653_ (
    .LO(la_data_out[42])
  );
  sky130_fd_sc_hd__conb_1 _654_ (
    .LO(la_data_out[43])
  );
  sky130_fd_sc_hd__conb_1 _655_ (
    .LO(la_data_out[44])
  );
  sky130_fd_sc_hd__conb_1 _656_ (
    .LO(la_data_out[45])
  );
  sky130_fd_sc_hd__conb_1 _657_ (
    .LO(la_data_out[46])
  );
  sky130_fd_sc_hd__conb_1 _658_ (
    .LO(la_data_out[47])
  );
  sky130_fd_sc_hd__conb_1 _659_ (
    .LO(la_data_out[48])
  );
  sky130_fd_sc_hd__conb_1 _660_ (
    .LO(la_data_out[49])
  );
  sky130_fd_sc_hd__conb_1 _661_ (
    .LO(la_data_out[50])
  );
  sky130_fd_sc_hd__conb_1 _662_ (
    .LO(la_data_out[51])
  );
  sky130_fd_sc_hd__conb_1 _663_ (
    .LO(la_data_out[52])
  );
  sky130_fd_sc_hd__conb_1 _664_ (
    .LO(la_data_out[53])
  );
  sky130_fd_sc_hd__conb_1 _665_ (
    .LO(la_data_out[54])
  );
  sky130_fd_sc_hd__conb_1 _666_ (
    .LO(la_data_out[55])
  );
  sky130_fd_sc_hd__conb_1 _667_ (
    .LO(la_data_out[56])
  );
  sky130_fd_sc_hd__conb_1 _668_ (
    .LO(la_data_out[57])
  );
  sky130_fd_sc_hd__conb_1 _669_ (
    .LO(la_data_out[58])
  );
  sky130_fd_sc_hd__conb_1 _670_ (
    .LO(la_data_out[59])
  );
  sky130_fd_sc_hd__conb_1 _671_ (
    .LO(la_data_out[60])
  );
  sky130_fd_sc_hd__conb_1 _672_ (
    .LO(la_data_out[61])
  );
  sky130_fd_sc_hd__conb_1 _673_ (
    .LO(la_data_out[62])
  );
  sky130_fd_sc_hd__conb_1 _674_ (
    .LO(la_data_out[63])
  );
  sky130_fd_sc_hd__conb_1 _675_ (
    .LO(la_data_out[64])
  );
  sky130_fd_sc_hd__conb_1 _676_ (
    .LO(la_data_out[65])
  );
  sky130_fd_sc_hd__conb_1 _677_ (
    .LO(la_data_out[66])
  );
  sky130_fd_sc_hd__conb_1 _678_ (
    .LO(la_data_out[67])
  );
  sky130_fd_sc_hd__conb_1 _679_ (
    .LO(la_data_out[68])
  );
  sky130_fd_sc_hd__conb_1 _680_ (
    .LO(la_data_out[69])
  );
  sky130_fd_sc_hd__conb_1 _681_ (
    .LO(la_data_out[70])
  );
  sky130_fd_sc_hd__conb_1 _682_ (
    .LO(la_data_out[71])
  );
  sky130_fd_sc_hd__conb_1 _683_ (
    .LO(la_data_out[72])
  );
  sky130_fd_sc_hd__conb_1 _684_ (
    .LO(la_data_out[73])
  );
  sky130_fd_sc_hd__conb_1 _685_ (
    .LO(la_data_out[74])
  );
  sky130_fd_sc_hd__conb_1 _686_ (
    .LO(la_data_out[75])
  );
  sky130_fd_sc_hd__conb_1 _687_ (
    .LO(la_data_out[76])
  );
  sky130_fd_sc_hd__conb_1 _688_ (
    .LO(la_data_out[77])
  );
  sky130_fd_sc_hd__conb_1 _689_ (
    .LO(la_data_out[78])
  );
  sky130_fd_sc_hd__conb_1 _690_ (
    .LO(la_data_out[79])
  );
  sky130_fd_sc_hd__conb_1 _691_ (
    .LO(la_data_out[80])
  );
  sky130_fd_sc_hd__conb_1 _692_ (
    .LO(la_data_out[81])
  );
  sky130_fd_sc_hd__conb_1 _693_ (
    .LO(la_data_out[82])
  );
  sky130_fd_sc_hd__conb_1 _694_ (
    .LO(la_data_out[83])
  );
  sky130_fd_sc_hd__conb_1 _695_ (
    .LO(la_data_out[84])
  );
  sky130_fd_sc_hd__conb_1 _696_ (
    .LO(la_data_out[85])
  );
  sky130_fd_sc_hd__conb_1 _697_ (
    .LO(la_data_out[86])
  );
  sky130_fd_sc_hd__conb_1 _698_ (
    .LO(la_data_out[87])
  );
  sky130_fd_sc_hd__conb_1 _699_ (
    .LO(la_data_out[88])
  );
  sky130_fd_sc_hd__conb_1 _700_ (
    .LO(la_data_out[89])
  );
  sky130_fd_sc_hd__conb_1 _701_ (
    .LO(la_data_out[90])
  );
  sky130_fd_sc_hd__conb_1 _702_ (
    .LO(la_data_out[91])
  );
  sky130_fd_sc_hd__conb_1 _703_ (
    .LO(la_data_out[92])
  );
  sky130_fd_sc_hd__conb_1 _704_ (
    .LO(la_data_out[93])
  );
  sky130_fd_sc_hd__conb_1 _705_ (
    .LO(la_data_out[94])
  );
  sky130_fd_sc_hd__conb_1 _706_ (
    .LO(la_data_out[95])
  );
  sky130_fd_sc_hd__conb_1 _707_ (
    .LO(la_data_out[96])
  );
  sky130_fd_sc_hd__conb_1 _708_ (
    .LO(la_data_out[97])
  );
  sky130_fd_sc_hd__conb_1 _709_ (
    .LO(la_data_out[98])
  );
  sky130_fd_sc_hd__conb_1 _710_ (
    .LO(la_data_out[99])
  );
  sky130_fd_sc_hd__conb_1 _711_ (
    .LO(la_data_out[100])
  );
  sky130_fd_sc_hd__conb_1 _712_ (
    .LO(la_data_out[101])
  );
  sky130_fd_sc_hd__conb_1 _713_ (
    .LO(la_data_out[102])
  );
  sky130_fd_sc_hd__conb_1 _714_ (
    .LO(la_data_out[103])
  );
  sky130_fd_sc_hd__conb_1 _715_ (
    .LO(la_data_out[104])
  );
  sky130_fd_sc_hd__conb_1 _716_ (
    .LO(la_data_out[105])
  );
  sky130_fd_sc_hd__conb_1 _717_ (
    .LO(la_data_out[106])
  );
  sky130_fd_sc_hd__conb_1 _718_ (
    .LO(la_data_out[107])
  );
  sky130_fd_sc_hd__conb_1 _719_ (
    .LO(la_data_out[108])
  );
  sky130_fd_sc_hd__conb_1 _720_ (
    .LO(la_data_out[109])
  );
  sky130_fd_sc_hd__conb_1 _721_ (
    .LO(la_data_out[110])
  );
  sky130_fd_sc_hd__conb_1 _722_ (
    .LO(la_data_out[111])
  );
  sky130_fd_sc_hd__conb_1 _723_ (
    .LO(la_data_out[112])
  );
  sky130_fd_sc_hd__conb_1 _724_ (
    .LO(la_data_out[113])
  );
  sky130_fd_sc_hd__conb_1 _725_ (
    .LO(la_data_out[114])
  );
  sky130_fd_sc_hd__conb_1 _726_ (
    .LO(la_data_out[115])
  );
  sky130_fd_sc_hd__conb_1 _727_ (
    .LO(la_data_out[116])
  );
  sky130_fd_sc_hd__conb_1 _728_ (
    .LO(la_data_out[117])
  );
  sky130_fd_sc_hd__conb_1 _729_ (
    .LO(la_data_out[118])
  );
  sky130_fd_sc_hd__conb_1 _730_ (
    .LO(la_data_out[119])
  );
  sky130_fd_sc_hd__conb_1 _731_ (
    .LO(la_data_out[120])
  );
  sky130_fd_sc_hd__conb_1 _732_ (
    .LO(la_data_out[121])
  );
  sky130_fd_sc_hd__conb_1 _733_ (
    .LO(la_data_out[122])
  );
  sky130_fd_sc_hd__conb_1 _734_ (
    .LO(la_data_out[123])
  );
  sky130_fd_sc_hd__conb_1 _735_ (
    .LO(la_data_out[124])
  );
  sky130_fd_sc_hd__conb_1 _736_ (
    .LO(la_data_out[125])
  );
  sky130_fd_sc_hd__conb_1 _737_ (
    .LO(la_data_out[126])
  );
  sky130_fd_sc_hd__conb_1 _738_ (
    .LO(la_data_out[127])
  );
  sky130_fd_sc_hd__buf_2 _739_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[15])
  );
  sky130_fd_sc_hd__buf_2 _740_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[16])
  );
  sky130_fd_sc_hd__buf_2 _741_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[17])
  );
  sky130_fd_sc_hd__buf_2 _742_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[18])
  );
  sky130_fd_sc_hd__buf_2 _743_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[19])
  );
  sky130_fd_sc_hd__buf_2 _744_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[20])
  );
  sky130_fd_sc_hd__buf_2 _745_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[21])
  );
  sky130_fd_sc_hd__buf_2 _746_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[22])
  );
  sky130_fd_sc_hd__buf_2 _747_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[23])
  );
  sky130_fd_sc_hd__buf_2 _748_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[24])
  );
  sky130_fd_sc_hd__buf_2 _749_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[25])
  );
  sky130_fd_sc_hd__buf_2 _750_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[26])
  );
  sky130_fd_sc_hd__buf_2 _751_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[27])
  );
  sky130_fd_sc_hd__buf_2 _752_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[28])
  );
  sky130_fd_sc_hd__buf_2 _753_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[29])
  );
  sky130_fd_sc_hd__buf_2 _754_ (
    .A(wbs_dat_o[31]),
    .X(wbs_dat_o[30])
  );
  sky130_fd_sc_hd__mux2_1 _755_ (
    .A0(_028_),
    .A1(\rdata[0] ),
    .S(_029_),
    .X(wbs_dat_o[0])
  );
  sky130_fd_sc_hd__mux2_1 _756_ (
    .A0(_030_),
    .A1(\rdata[1] ),
    .S(_029_),
    .X(wbs_dat_o[1])
  );
  sky130_fd_sc_hd__mux2_1 _757_ (
    .A0(_031_),
    .A1(\rdata[2] ),
    .S(_029_),
    .X(wbs_dat_o[2])
  );
  sky130_fd_sc_hd__mux2_1 _758_ (
    .A0(_032_),
    .A1(\rdata[3] ),
    .S(_029_),
    .X(wbs_dat_o[3])
  );
  sky130_fd_sc_hd__mux2_1 _759_ (
    .A0(_033_),
    .A1(\rdata[4] ),
    .S(_029_),
    .X(wbs_dat_o[4])
  );
  sky130_fd_sc_hd__mux2_1 _760_ (
    .A0(_034_),
    .A1(\rdata[5] ),
    .S(_029_),
    .X(wbs_dat_o[5])
  );
  sky130_fd_sc_hd__mux2_1 _761_ (
    .A0(_035_),
    .A1(\rdata[6] ),
    .S(_029_),
    .X(wbs_dat_o[6])
  );
  sky130_fd_sc_hd__mux2_1 _762_ (
    .A0(_036_),
    .A1(\rdata[7] ),
    .S(_029_),
    .X(wbs_dat_o[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _763_ (
    .CLK(wb_clk_i),
    .D(_042_),
    .Q(wbs_ack_o)
  );
  sky130_fd_sc_hd__dfxtp_2 _764_ (
    .CLK(wb_clk_i),
    .D(_043_),
    .Q(\pcmclk.count[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _765_ (
    .CLK(wb_clk_i),
    .D(_044_),
    .Q(\pcmclk.count[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _766_ (
    .CLK(wb_clk_i),
    .D(_045_),
    .Q(\pcmclk.count[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _767_ (
    .CLK(wb_clk_i),
    .D(_046_),
    .Q(\pcmclk.count[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _768_ (
    .CLK(wb_clk_i),
    .D(_047_),
    .Q(\pcmclk.count[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _769_ (
    .CLK(wb_clk_i),
    .D(_048_),
    .Q(\pcmclk.count[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _770_ (
    .CLK(wb_clk_i),
    .D(_049_),
    .Q(\pcmclk.count[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _771_ (
    .CLK(wb_clk_i),
    .D(_050_),
    .Q(\pcmclk.count[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _772_ (
    .CLK(wb_clk_i),
    .D(_051_),
    .Q(\pcmclk.count[8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _773_ (
    .CLK(wb_clk_i),
    .D(_052_),
    .Q(\pcmclk.count[9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _774_ (
    .CLK(wb_clk_i),
    .D(_053_),
    .Q(\mic.cnt1[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _775_ (
    .CLK(wb_clk_i),
    .D(_054_),
    .Q(\mic.cnt1[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _776_ (
    .CLK(wb_clk_i),
    .D(_055_),
    .Q(\mic.cnt1[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _777_ (
    .CLK(wb_clk_i),
    .D(_056_),
    .Q(\mic.cnt1[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _778_ (
    .CLK(_037_),
    .D(_057_),
    .Q(\mic.cnt2[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _779_ (
    .CLK(_038_),
    .D(_058_),
    .Q(\mic.cnt2[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _780_ (
    .CLK(_039_),
    .D(_059_),
    .Q(\mic.cnt2[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _781_ (
    .CLK(_040_),
    .D(_060_),
    .Q(\mic.cnt2[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _782_ (
    .CLK(wb_clk_i),
    .D(_061_),
    .Q(\pcmclk.ce_pcm )
  );
  sky130_fd_sc_hd__dfxtp_2 _783_ (
    .CLK(wb_clk_i),
    .D(_062_),
    .Q(\rdata[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _784_ (
    .CLK(wb_clk_i),
    .D(_063_),
    .Q(\rdata[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _785_ (
    .CLK(wb_clk_i),
    .D(_064_),
    .Q(\rdata[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _786_ (
    .CLK(wb_clk_i),
    .D(_065_),
    .Q(\rdata[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _787_ (
    .CLK(wb_clk_i),
    .D(_066_),
    .Q(\rdata[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _788_ (
    .CLK(wb_clk_i),
    .D(_067_),
    .Q(\rdata[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _789_ (
    .CLK(wb_clk_i),
    .D(_068_),
    .Q(\rdata[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _790_ (
    .CLK(wb_clk_i),
    .D(_069_),
    .Q(\rdata[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _791_ (
    .CLK(wb_clk_i),
    .D(_070_),
    .Q(\pcmclk.prescaler[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _792_ (
    .CLK(wb_clk_i),
    .D(_071_),
    .Q(\pcmclk.prescaler[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _793_ (
    .CLK(wb_clk_i),
    .D(_072_),
    .Q(\pcmclk.prescaler[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _794_ (
    .CLK(wb_clk_i),
    .D(_073_),
    .Q(\pcmclk.prescaler[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _795_ (
    .CLK(wb_clk_i),
    .D(_074_),
    .Q(\pcmclk.prescaler[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _796_ (
    .CLK(wb_clk_i),
    .D(_075_),
    .Q(\pcmclk.prescaler[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _797_ (
    .CLK(wb_clk_i),
    .D(_076_),
    .Q(\pcmclk.prescaler[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _798_ (
    .CLK(wb_clk_i),
    .D(_077_),
    .Q(\pcmclk.prescaler[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _799_ (
    .CLK(wb_clk_i),
    .D(_078_),
    .Q(\mic.tmp1 )
  );
  sky130_fd_sc_hd__dfxtp_2 _800_ (
    .CLK(_041_),
    .D(_079_),
    .Q(\mic.tmp2 )
  );
  sky130_fd_sc_hd__dlxtn_1 _801_ (
    .D(_000_),
    .GATE_N(_019_),
    .Q(\valid_i[0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _802_ (
    .D(_005_),
    .GATE_N(_020_),
    .Q(\valid_i[1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _803_ (
    .D(_006_),
    .GATE_N(_021_),
    .Q(\valid_i[2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _804_ (
    .D(_007_),
    .GATE_N(_022_),
    .Q(\valid_i[3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _805_ (
    .D(_008_),
    .GATE_N(_023_),
    .Q(\valid_i[4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _806_ (
    .D(_009_),
    .GATE_N(_024_),
    .Q(\valid_i[5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _807_ (
    .D(_010_),
    .GATE_N(_025_),
    .Q(\valid_i[6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _808_ (
    .D(_011_),
    .GATE_N(_026_),
    .Q(\valid_i[7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _809_ (
    .D(_012_),
    .GATE_N(_027_),
    .Q(\valid_i[8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _810_ (
    .D(_013_),
    .GATE_N(_014_),
    .Q(\valid_i[9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _811_ (
    .D(_001_),
    .GATE_N(_015_),
    .Q(\valid_i[11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _812_ (
    .D(_002_),
    .GATE_N(_016_),
    .Q(\valid_i[12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _813_ (
    .D(_003_),
    .GATE_N(_017_),
    .Q(\valid_i[13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _814_ (
    .D(_004_),
    .GATE_N(_018_),
    .Q(\valid_i[14] )
  );
  SonarOnChip soc1 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[0] ),
    .hi_z(\hi_z[0] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[1]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[0] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc10 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[9] ),
    .hi_z(\hi_z[9] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[10]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[9] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc11 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[10] ),
    .hi_z(\hi_z[10] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[11]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(_258_),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc12 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[11] ),
    .hi_z(\hi_z[11] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[12]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[11] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc13 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[12] ),
    .hi_z(\hi_z[12] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[13]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[12] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc14 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[13] ),
    .hi_z(\hi_z[13] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[14]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[13] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc15 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[14] ),
    .hi_z(\hi_z[14] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[15]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[14] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc2 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[1] ),
    .hi_z(\hi_z[1] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[2]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[1] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc3 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[2] ),
    .hi_z(\hi_z[2] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[3]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[2] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc4 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[3] ),
    .hi_z(\hi_z[3] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[4]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[3] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc5 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[4] ),
    .hi_z(\hi_z[4] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[5]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[4] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc6 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[5] ),
    .hi_z(\hi_z[5] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[6]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[5] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc7 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[6] ),
    .hi_z(\hi_z[6] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[7]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[6] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc8 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[7] ),
    .hi_z(\hi_z[7] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[8]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[7] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
  SonarOnChip soc9 (
    .ce_pcm(\pcmclk.ce_pcm ),
    .ce_pdm(\mic.ce_pdm ),
    .cmp(\cmp[8] ),
    .hi_z(\hi_z[8] ),
    .mclear(la_data_in[0]),
    .pdm_data_i(io_in[9]),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wb_valid_i(\valid_i[8] ),
    .wbs_ack_o(ack_o),
    .wbs_adr_i({ \addr[3] , \addr[2] , \addr[1] , wbs_adr_i[2] }),
    .wbs_dat_i({ wbs_dat_i[31], wbs_dat_i[14:0] }),
    .wbs_dat_o({ \dat_o[15] , \dat_o[14] , \dat_o[13] , \dat_o[12] , \dat_o[11] , \dat_o[10] , \dat_o[9] , \dat_o[8] , \dat_o[7] , \dat_o[6] , \dat_o[5] , \dat_o[4] , \dat_o[3] , \dat_o[2] , \dat_o[1] , \dat_o[0]  }),
    .wbs_strb_i(strb_i)
  );
endmodule
